[build]
  functions = "netlify/functions"
  publish   = "public"

[functions]
  external_node_modules = ["express"]

[[redirects]]
  from   = "/(.*)"
  to     = "/.netlify/functions/server"
  status = 200
  force  = true