[build]
  functions = "netlify/functions"
  publish   = "public"

[dev]
  framework  = "#custom"
  command    = "npm start"
  port       = 8888
  targetPort = 3000
  publish    = "public"
  functions  = "netlify/functions"

[[redirects]]
  from   = "/(.*)"
  to     = "/.netlify/functions/server"
  status = 200
  force  = true